# Generated by Django 5.2.8 on 2025-11-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image_product_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
