# Generated by Django 5.2.8 on 2025-11-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('transaction_reference', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
