[
  {
    name: "Smartphones & Accessories",
    slug: "smartphones-accessories",
    description: "The latest mobile technology and complementary gear.",
    products: [
      {
        name: "Flagship Pro Smartphone (Model X)",
        slug: "flagship-pro-smartphone-x",
        price: "999.00",
        description: "Next-generation smartphone with triple camera.",
        brand: "TechCorp",
      },
      {
        name: "Essential Phone Case (Clear)",
        slug: "essential-phone-case-clear",
        price: "15.99",
        description: "Durable clear protective case.",
        brand: "GuardCo",
      },
      {
        name: "Ultra-Fast Charging Cable (USB-C)",
        slug: "ultrafast-charging-cable-usbc",
        price: "9.99",
        description: "2-meter braided USB-C cable.",
        brand: "LinkFast",
      },
      {
        name: "Portable 10,000mAh Power Bank",
        slug: "portable-power-bank-10000",
        price: "45.00",
        description: "Charge on the go with high capacity.",
        brand: "JuiceBox",
      },
      {
        name: "Wireless Charging Pad (Fast)",
        slug: "wireless-charging-pad-fast",
        price: "29.99",
        description: "Sleek pad supporting 15W fast charge.",
        brand: "TechCorp",
      },
      {
        name: "Bluetooth Earbuds (Noise Cancelling)",
        slug: "bluetooth-earbuds-nc",
        price: "129.00",
        description: "Immersive sound with active noise cancellation.",
        brand: "SoundWave",
      },
      {
        name: "Phone Screen Protector (Tempered Glass)",
        slug: "phone-screen-protector-glass",
        price: "8.50",
        description: "Scratch-resistant tempered glass.",
        brand: "GuardCo",
      },
      {
        name: "Pop Socket Phone Grip (Marble)",
        slug: "popsocket-phone-grip-marble",
        price: "12.00",
        description: "Secure grip and stylish stand.",
        brand: "GripIt",
      },
      {
        name: "Car Phone Mount (Air Vent)",
        slug: "car-phone-mount-air-vent",
        price: "21.00",
        description: "Secure mount for hands-free driving.",
        brand: "DriveSafe",
      },
      {
        name: "Smartwatch (Fitness Tracker)",
        slug: "smartwatch-fitness-tracker",
        price: "199.99",
        description: "Track steps, heart rate, and notifications.",
        brand: "HealthTech",
      },
      {
        name: "Stylus Pen for Tablets/Phones",
        slug: "stylus-pen-tablets",
        price: "14.99",
        description: "Precise input for creative work.",
        brand: "WriteRight",
      },
      {
        name: "Micro SD Card (256GB, U3)",
        slug: "microsd-card-256gb",
        price: "39.99",
        description: "Expand your storage quickly.",
        brand: "SpeedyDrive",
      },
      {
        name: "USB-C to HDMI Adapter",
        slug: "usbc-to-hdmi-adapter",
        price: "19.99",
        description: "Connect your phone to an external display.",
        brand: "LinkFast",
      },
      {
        name: "Rugged Outdoor Phone Case",
        slug: "rugged-outdoor-phone-case",
        price: "24.99",
        description: "Heavy duty protection against drops and water.",
        brand: "GuardCo",
      },
      {
        name: "Selfie Ring Light",
        slug: "selfie-ring-light",
        price: "16.00",
        description: "Perfect lighting for photos and videos.",
        brand: "SnapHappy",
      },
      {
        name: "Phone Camera Lens Kit (3-in-1)",
        slug: "phone-camera-lens-kit",
        price: "28.00",
        description: "Wide angle, macro, and fish eye lenses.",
        brand: "ProLens",
      },
      {
        name: "Screen Cleaning Kit",
        slug: "screen-cleaning-kit",
        price: "6.99",
        description: "Streak-free cleaner for all screens.",
        brand: "CleanSmart",
      },
      {
        name: "Silicone Charging Cable Ties",
        slug: "silicone-charging-cable-ties",
        price: "4.99",
        description: "Keep cables organized and tidy.",
        brand: "LinkFast",
      },
      {
        name: "Phone Cooling Fan Attachment",
        slug: "phone-cooling-fan-attachment",
        price: "19.99",
        description: "Prevents overheating during intense use.",
        brand: "GameOn",
      },
      {
        name: "Vintage Leather Wallet Phone Case",
        slug: "vintage-leather-wallet-case",
        price: "34.99",
        description: "Wallet and phone case in one, real leather.",
        brand: "HauteBags",
      },
    ],
  },
  {
    name: "Laptops & Computing",
    slug: "laptops-computing",
    description: "Powerful machines for work, study, and play.",
    products: [
      {
        name: "Lightweight Productivity Laptop (13-inch)",
        slug: "lightweight-productivity-laptop",
        price: "1100.00",
        description: "Core i7, 16GB RAM, all-day battery.",
        brand: "AeroTech",
      },
      {
        name: "Mechanical Keyboard (RGB Backlit)",
        slug: "mechanical-keyboard-rgb",
        price: "75.00",
        description: "Tactile feel for superior typing experience.",
        brand: "KeyMaster",
      },
      {
        name: "27-inch 4K Monitor",
        slug: "27inch-4k-monitor",
        price: "350.00",
        description: "Vibrant colors and high resolution.",
        brand: "PixelDisplay",
      },
      {
        name: "External Solid State Drive (1TB)",
        slug: "external-ssd-1tb",
        price: "90.00",
        description: "Fast, reliable external storage.",
        brand: "SpeedyDrive",
      },
      {
        name: "Ergonomic Office Chair",
        slug: "ergonomic-office-chair",
        price: "250.00",
        description: "Full back support and adjustable height.",
        brand: "SitWell",
      },
      {
        name: "Wireless Ergonomic Mouse",
        slug: "wireless-ergonomic-mouse",
        price: "29.99",
        description: "A comfortable mouse designed for long hours of use.",
        brand: "TechCorp",
      },
      {
        name: "Laptop Cooling Pad (Dual Fan)",
        slug: "laptop-cooling-pad-dualfan",
        price: "25.00",
        description: "Prevents laptop from overheating.",
        brand: "CoolMaster",
      },
      {
        name: "USB Hub (4-port USB 3.0)",
        slug: "usb-hub-4port",
        price: "19.99",
        description: "Expand your ports easily.",
        brand: "LinkFast",
      },
      {
        name: "Laptop Sleeve Case (13-inch, Grey)",
        slug: "laptop-sleeve-case-13inch",
        price: "15.00",
        description: "Padded protection for your laptop.",
        brand: "GuardCo",
      },
      {
        name: "Gaming PC (High End Build)",
        slug: "gaming-pc-highend",
        price: "2500.00",
        description: "Top tier components for maximum performance.",
        brand: "GameOn",
      },
      {
        name: "Webcam Cover Slider (3 pack)",
        slug: "webcam-cover-slider-3pack",
        price: "5.99",
        description: "Ensure your privacy easily.",
        brand: "PrivacyGuard",
      },
      {
        name: "External Hard Drive (4TB HDD)",
        slug: "external-hard-drive-4tb",
        price: "110.00",
        description: "Massive storage for backups and files.",
        brand: "StorageSolutions",
      },
      {
        name: "Monitor Arm Mount (Single Screen)",
        slug: "monitor-arm-mount",
        price: "65.00",
        description: "Free up desk space and adjust height easily.",
        brand: "MountEasy",
      },
      {
        name: "Gaming Mouse Pad (Large RGB)",
        slug: "gaming-mouse-pad-large-rgb",
        price: "30.00",
        description: "Smooth surface with customizable RGB lighting.",
        brand: "GameOn",
      },
      {
        name: "HDMI Cable (4K 60Hz 2m)",
        slug: "hdmi-cable-4k-2m",
        price: "12.00",
        description: "High speed cable for optimal display.",
        brand: "LinkFast",
      },
      {
        name: "Laptop Stand (Adjustable Aluminum)",
        slug: "laptop-stand-adjustable-aluminum",
        price: "40.00",
        description: "Improves airflow and ergonomics.",
        brand: "CoolMaster",
      },
      {
        name: "Noise Cancelling Headset w/ Mic",
        slug: "noise-cancelling-headset-mic",
        price: "95.00",
        description: "Clear communication and focus for calls/gaming.",
        brand: "SoundWave",
      },
      {
        name: "Graphic Drawing Tablet",
        slug: "graphic-drawing-tablet",
        price: "150.00",
        description: "Unleash your creativity with digital art.",
        brand: "DrawTech",
      },
      {
        name: "Networking WiFi 6 Router",
        slug: "networking-wifi6-router",
        price: "130.00",
        description: "Next level network speed and coverage.",
        brand: "NetSpeed",
      },
      {
        name: "VR Headset (Basic Kit)",
        slug: "vr-headset-basic-kit",
        price: "299.00",
        description: "Entry level virtual reality experience.",
        brand: "FuturePlay",
      },
    ],
  },
  {
    name: "Fashion: Menswear",
    slug: "menswear",
    description: "Style essentials for every occasion.",
    products: [
      {
        name: "Classic Fit Denim Jeans",
        slug: "classic-fit-denim-jeans",
        price: "49.99",
        description: "Straight cut, durable denim.",
        brand: "DenimCo",
      },
      {
        name: "Linen Button-Down Shirt (Blue)",
        slug: "linen-button-down-blue",
        price: "35.00",
        description: "Lightweight linen perfect for summer.",
        brand: "CoastalStyles",
      },
      {
        name: "Leather Chelsea Boots",
        slug: "leather-chelsea-boots",
        price: "120.00",
        description: "Hand-stitched leather boots, comfortable fit.",
        brand: "StrideRite",
      },
      {
        name: "Wool Blend Beanie (Grey)",
        slug: "wool-blend-beanie-grey",
        price: "18.00",
        description: "Warm and stylish, perfect for winter.",
        brand: "KnitWorks",
      },
      {
        name: "Slim Fit Chino Pants (Khaki)",
        slug: "slim-fit-chino-pants-khaki",
        price: "40.00",
        description: "Versatile smart-casual trousers.",
        brand: "DenimCo",
      },
      {
        name: "Merino Wool Crewneck Sweater",
        slug: "merino-wool-crewneck-sweater",
        price: "75.00",
        description: "Soft, breathable, temperature-regulating wool.",
        brand: "KnitWorks",
      },
      {
        name: "Canvas Backpack (Minimalist)",
        slug: "canvas-backpack-minimalist",
        price: "55.00",
        description: "Simple design, durable canvas, ideal for daily use.",
        brand: "CarryWell",
      },
      {
        name: "Classic White Sneakers",
        slug: "classic-white-sneakers",
        price: "60.00",
        description: "Clean white leather sneakers for any outfit.",
        brand: "StrideRite",
      },
      {
        name: "Formal Dress Shirt (White Cotton)",
        slug: "formal-dress-shirt-white-cotton",
        price: "45.00",
        description: "Crisp cotton shirt for business or events.",
        brand: "TailoredFit",
      },
      {
        name: "Silk Tie (Navy Blue)",
        slug: "silk-tie-navy-blue",
        price: "28.00",
        description: "100% silk tie, perfect finish to a suit.",
        brand: "TailoredFit",
      },
      {
        name: "Sporty Track Jacket (Black)",
        slug: "sporty-track-jacket-black",
        price: "39.99",
        description: "Breathable fabric, zip-up front, active wear.",
        brand: "ActiveStep",
      },
      {
        name: "Swim Shorts (Tropical Pattern)",
        slug: "swim-shorts-tropical-pattern",
        price: "22.00",
        description: "Quick-dry fabric for beach or pool.",
        brand: "CoastalStyles",
      },
      {
        name: "Aviator Sunglasses",
        slug: "aviator-sunglasses",
        price: "32.00",
        description: "Classic metal frame aviators, UV protection.",
        brand: "ShadeCo",
      },
      {
        name: "Leather Biker Jacket",
        slug: "leather-biker-jacket",
        price: "180.00",
        description: "Real leather jacket, timeless style.",
        brand: "HauteBags",
      },
      {
        name: "Chunky Knit Cardigan (Brown)",
        slug: "chunky-knit-cardigan-brown",
        price: "55.00",
        description: "Warm and cozy, perfect autumn layer.",
        brand: "KnitWorks",
      },
      {
        name: "Slim Fit Corduroy Pants (Green)",
        slug: "slim-fit-corduroy-pants-green",
        price: "42.00",
        description: "Textured corduroy for a different look.",
        brand: "DenimCo",
      },
      {
        name: "Flannel Shirt (Red Plaid)",
        slug: "flannel-shirt-red-plaid",
        price: "30.00",
        description: "Soft brushed flannel, warm and casual.",
        brand: "CoastalStyles",
      },
      {
        name: "Running Tights (Compression)",
        slug: "running-tights-compression",
        price: "45.00",
        description: "Muscle support for running and workouts.",
        brand: "ActiveStep",
      },
      {
        name: "Waterproof Rain Jacket (Yellow)",
        slug: "waterproof-rain-jacket-yellow",
        price: "70.00",
        description: "Fully waterproof, lightweight shell.",
        brand: "TrailGear",
      },
      {
        name: "Smart Casual Blazer (Navy)",
        slug: "smart-casual-blazer-navy",
        price: "90.00",
        description: "Versatile blazer for a refined look.",
        brand: "TailoredFit",
      },
    ],
  },
  {
    name: "Fashion: Womenswear",
    slug: "womenswear",
    description: "Elegant and casual styles for women.",
    products: [
      {
        name: "Floral Summer Dress (Midi)",
        slug: "floral-summer-dress-midi",
        price: "65.00",
        description: "Lightweight flowy dress with floral pattern.",
        brand: "Blossom",
      },
      {
        name: "High-Waisted Skinny Jeans",
        slug: "high-waisted-skinny-jeans",
        price: "55.00",
        description: "Stretchy fit, classic wash.",
        brand: "DenimCo",
      },
      {
        name: "Leather Crossbody Bag (Black)",
        slug: "leather-crossbody-bag-black",
        price: "85.00",
        description: "Compact and stylish bag, real leather.",
        brand: "HauteBags",
      },
      {
        name: "Knitted Cardigan (Beige)",
        slug: "knitted-cardigan-beige",
        price: "40.00",
        description: "Cozy open-front cardigan.",
        brand: "KnitWorks",
      },
      {
        name: "Silk Blouse (Cream)",
        slug: "silk-blouse-cream",
        price: "70.00",
        description: "Elegant silk top for work or evening wear.",
        brand: "Blossom",
      },
      {
        name: "A-Line Midi Skirt (Red)",
        slug: "a-line-midi-skirt-red",
        price: "45.00",
        description: "Flowy skirt perfect for a smart-casual look.",
        brand: "CoastalStyles",
      },
      {
        name: "Stiletto Heels (Black Patent)",
        slug: "stiletto-heels-black-patent",
        price: "90.00",
        description: "Classic pointed toe stiletto heels.",
        brand: "StrideRite",
      },
      {
        name: "Wool Coat (Camel)",
        slug: "wool-coat-camel",
        price: "140.00",
        description: "Warm, long wool blend coat for winter.",
        brand: "KnitWorks",
      },
      {
        name: "Yoga Leggings (Black High-WaWaist)",
        slug: "yoga-leggings-black-highwaist",
        price: "35.00",
        description: "Stretchy, comfortable high-waisted leggings.",
        brand: "ActiveStep",
      },
      {
        name: "Beach Cover Up Sarong (White)",
        slug: "beach-cover-up-sarong-white",
        price: "19.99",
        description: "Lightweight sarong for beach holidays.",
        brand: "CoastalStyles",
      },
      {
        name: "Gold Hoop Earrings (Large)",
        slug: "gold-hoop-earrings-large",
        price: "28.00",
        description: "Chunky gold hoops, hypoallergenic material.",
        brand: "Sparkle",
      },
      {
        name: "Leather Shoulder Bag (Tan)",
        slug: "leather-shoulder-bag-tan",
        price: "110.00",
        description: "Medium sized leather bag for daily use.",
        brand: "HauteBags",
      },
      {
        name: "Denim Cutoff Shorts (Vintage Blue)",
        slug: "denim-cutoff-shorts-vintage-blue",
        price: "30.00",
        description: "Classic high-waisted denim shorts.",
        brand: "DenimCo",
      },
      {
        name: "Lace Bodysuit (Black)",
        slug: "lace-bodysuit-black",
        price: "25.00",
        description: "Elegant lace bodysuit, perfect layering piece.",
        brand: "Blossom",
      },
      {
        name: "Running Sneakers (Pink)",
        slug: "running-sneakers-pink",
        price: "85.00",
        description: "Supportive running shoes in a vibrant color.",
        brand: "ActiveStep",
      },
      {
        name: "Cashmere Scarf (Burgundy)",
        slug: "cashmere-scarf-burgundy",
        price: "60.00",
        description: "Luxuriously soft and warm cashmere scarf.",
        brand: "KnitWorks",
      },
      {
        name: "Evening Gown (Navy Silk)",
        slug: "evening-gown-navy-silk",
        price: "220.00",
        description: "Stunning floor-length silk gown for formal events.",
        brand: "TailoredFit",
      },
      {
        name: "Ballet Flats (Red Leather)",
        slug: "ballet-flats-red-leather",
        price: "55.00",
        description: "Comfortable leather ballet flats.",
        brand: "StrideRite",
      },
      {
        name: "Sunglasses (Cat Eye Frame)",
        slug: "sunglasses-cat-eye-frame",
        price: "35.00",
        description: "Stylish retro cat-eye sunglasses.",
        brand: "ShadeCo",
      },
      {
        name: "Bikini Set (Minimalist Black)",
        slug: "bikini-set-minimalist-black",
        price: "42.00",
        description: "Classic triangle bikini top and bottoms.",
        brand: "CoastalStyles",
      },
    ],
  },
  {
    name: "Home Goods",
    slug: "home-goods",
    description: "Decorations and essentials for the perfect home.",
    products: [
      {
        name: "Velvet Throw Pillow (Teal)",
        slug: "velvet-throw-pillow-teal",
        price: "22.00",
        description: "Soft velvet pillow for your sofa.",
        brand: "CozyHome",
      },
      {
        name: "Minimalist Ceramic Vase",
        slug: "minimalist-ceramic-vase",
        price: "30.00",
        description: "Handmade ceramic vase, matte finish.",
        brand: "ArtisanCrafts",
      },
      {
        name: "Aroma Diffuser (Wood Grain)",
        slug: "aroma-diffuser-wood-grain",
        price: "45.00",
        description: "Ultrasonic diffuser with LED light.",
        brand: "ZenLiving",
      },
      {
        name: "Soft Waffle Bath Towel Set",
        slug: "soft-waffle-bath-towel-set",
        price: "50.00",
        description: "Luxurious Egyptian cotton towel set.",
        brand: "BathEssentials",
      },
      {
        name: "Queen Size Linen Bed Sheets (Grey)",
        slug: "queen-size-linen-bed-sheets-grey",
        price: "120.00",
        description: "Breathable linen sheets for comfort.",
        brand: "CozyHome",
      },
      {
        name: "Stainless Steel Kitchen Utensil Set (10pc)",
        slug: "stainless-steel-kitchen-utensil-set",
        price: "39.99",
        description: "Durable and stylish kitchen tools.",
        brand: "CookMaster",
      },
      {
        name: "Robot Vacuum Cleaner",
        slug: "robot-vacuum-cleaner",
        price: "200.00",
        description: "Automated cleaning for smart homes.",
        brand: "CleanSmart",
      },
      {
        name: "Framed Abstract Wall Art (Large)",
        slug: "framed-abstract-wall-art-large",
        price: "85.00",
        description: "Modern abstract print in a wooden frame.",
        brand: "ArtisanCrafts",
      },
      {
        name: "LED Smart Light Bulbs (4 Pack)",
        slug: "led-smart-light-bulbs-4pack",
        price: "40.00",
        description: "App controlled, customizable colors and brightness.",
        brand: "ZenLiving",
      },
      {
        name: "Memory Foam Pillow (Standard)",
        slug: "memory-foam-pillow-standard",
        price: "35.00",
        description: "Ergonomic support for restful sleep.",
        brand: "SitWell",
      },
      {
        name: "Cast Iron Dutch Oven (Red)",
        slug: "cast-iron-dutch-oven-red",
        price: "110.00",
        description: "Perfect for slow cooking and baking.",
        brand: "CookMaster",
      },
      {
        name: "Electric Kettle (Matte Black)",
        slug: "electric-kettle-matte-black",
        price: "55.00",
        description: "Fast boiling electric kettle with auto shut-off.",
        brand: "KitchenAid",
      },
      {
        name: "Bamboo Bath Caddy Tray",
        slug: "bamboo-bath-caddy-tray",
        price: "25.00",
        description: "Relax in style with a tray for books/drinks.",
        brand: "BathEssentials",
      },
      {
        name: "Minimalist Coffee Table (Oak Wood)",
        slug: "minimalist-coffee-table-oak-wood",
        price: "150.00",
        description: "Solid oak wood coffee table, modern design.",
        brand: "CozyHome",
      },
      {
        name: "Scented Candle Set (Lavender & Vanilla)",
        slug: "scented-candle-set-lavender-vanilla",
        price: "18.00",
        description: "Relaxing scents in decorative jars.",
        brand: "ZenLiving",
      },
      {
        name: "Hand-Woven Area Rug (Grey/White)",
        slug: "hand-woven-area-rug-grey-white",
        price: "199.00",
        description: "Soft wool blend rug, adds texture to any room.",
        brand: "ArtisanCrafts",
      },
      {
        name: "Glass Food Storage Containers (Set of 5)",
        slug: "glass-food-storage-containers-set5",
        price: "30.00",
        description: "Airtight glass containers, oven and freezer safe.",
        brand: "CookMaster",
      },
      {
        name: "Digital Bathroom Scale",
        slug: "digital-bathroom-scale",
        price: "29.99",
        description: "Precise weight measurement with digital display.",
        brand: "HealthTech",
      },
      {
        name: "Modern Desk Lamp (Black Metal)",
        slug: "modern-desk-lamp-black-metal",
        price: "40.00",
        description: "Adjustable desk lamp with LED light.",
        brand: "CozyHome",
      },
      {
        name: "Microfiber Cleaning Cloths (10 Pack)",
        slug: "microfiber-cleaning-cloths-10pack",
        price: "12.00",
        description: "Highly absorbent cloths for streak-free cleaning.",
        brand: "CleanSmart",
      },
    ],
  },
  {
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Equipment and apparel for active lifestyles and adventure.",
    products: [
      {
        name: "High-Performance Running Shoes",
        slug: "high-performance-running-shoes",
        price: "110.00",
        description: "Lightweight shoes with superior cushioning.",
        brand: "ActiveStep",
      },
      {
        name: "Camping Tent (2-Person)",
        slug: "camping-tent-2person",
        price: "89.00",
        description: "Waterproof tent, easy to set up in 5 minutes.",
        brand: "TrailGear",
      },
      {
        name: "Yoga Mat (Eco-Friendly)",
        slug: "yoga-mat-eco-friendly",
        price: "29.99",
        description: "Non-slip TPE material, extra thick.",
        brand: "ZenFlow",
      },
      {
        name: "Stainless Steel Water Bottle (1L)",
        slug: "stainless-steel-water-bottle-1l",
        price: "22.00",
        description: "Keeps drinks cold for 24 hours.",
        brand: "HydratePro",
      },
      {
        name: "Hiking Backpack (40L)",
        slug: "hiking-backpack-40l",
        price: "75.00",
        description:
          "Large capacity backpack for day hikes or overnight trips.",
        brand: "TrailGear",
      },
      {
        name: "Bluetooth Fitness Tracker Watch",
        slug: "bluetooth-fitness-tracker-watch",
        price: "45.00",
        description: "Monitor heart rate, steps, and sleep.",
        brand: "HealthTech",
      },
      {
        name: "Resistance Band Set (5 Levels)",
        slug: "resistance-band-set-5levels",
        price: "19.99",
        description: "Versatile set for strength training at home.",
        brand: "ActiveStep",
      },
      {
        name: "Camping Headlamp (Rechargeable LED)",
        slug: "camping-headlamp-rechargeable",
        price: "15.00",
        description: "Bright headlamp for hands-free lighting.",
        brand: "TrailGear",
      },
      {
        name: "Soccer Ball (Size 5)",
        slug: "soccer-ball-size-5",
        price: "24.00",
        description: "Durable training soccer ball.",
        brand: "GameOn",
      },
      {
        name: "Yoga Block (Cork)",
        slug: "yoga-block-cork",
        price: "12.00",
        description: "Firm support for yoga poses, eco-friendly cork material.",
        brand: "ZenFlow",
      },
      {
        name: "Outdoor Camping Hammock (Double)",
        slug: "outdoor-camping-hammock-double",
        price: "35.00",
        description: "Lightweight and strong nylon hammock.",
        brand: "TrailGear",
      },
      {
        name: "Running Shorts (Quick Dry)",
        slug: "running-shorts-quick-dry",
        price: "28.00",
        description: "Quick-dry fabric for maximum comfort during runs.",
        brand: "ActiveStep",
      },
      {
        name: "Bicycle Pump (Floor Standing)",
        slug: "bicycle-pump-floor-standing",
        price: "20.00",
        description: "Easy to use floor pump with pressure gauge.",
        brand: "RideSafe",
      },
      {
        name: "Ski Goggles (UV Protection)",
        slug: "ski-goggles-uv-protection",
        price: "60.00",
        description: "Anti-fog goggles for skiing and snowboarding.",
        brand: "ShadeCo",
      },
      {
        name: "Dumbbell Set (Adjustable 5-50 lbs)",
        slug: "dumbbell-set-adjustable-5-50lbs",
        price: "199.00",
        description: "Adjustable weights saving space in your home gym.",
        brand: "HealthTech",
      },
      {
        name: "Insulated Lunch Box",
        slug: "insulated-lunch-box",
        price: "18.00",
        description: "Keeps food hot or cold, durable design.",
        brand: "CarryWell",
      },
      {
        name: "Fishing Rod and Reel Combo",
        slug: "fishing-rod-reel-combo",
        price: "70.00",
        description: "Beginner-friendly fishing setup for freshwater fishing.",
        brand: "Outdoorsman",
      },
      {
        name: "Portable Camping Chair",
        slug: "portable-camping-chair",
        price: "25.00",
        description: "Foldable, durable chair for camping or events.",
        brand: "TrailGear",
      },
      {
        name: "Basketball (Official Size)",
        slug: "basketball-official-size",
        price: "30.00",
        description: "Official size and weight for serious play.",
        brand: "GameOn",
      },
      {
        name: "Sun Hat (Wide Brim)",
        slug: "sun-hat-wide-brim",
        price: "16.00",
        description: "Maximum sun protection for outdoor activities.",
        brand: "ShadeCo",
      },
    ],
  },
];
